### ISSUE TITLE
PosPage Markup

### ISSUE THREAD

**Issue by rlatkd** [ssg-salesync/frontend#38]
## Description
- PosPage Markup

## Todo
- [x] PosCategory 컴포넌트 재구성
- [x] PosItem 컴포넌트 재구성
- [x] 컴포넌트 연동 확인

## ETC
-
