### ISSUE TITLE
MyPage, PosPage 추가 기능 개선

### ISSUE THREAD

**Issue by rlatkd** [ssg-salesync/frontend#65]
## Description
- MyPage, PosPage 추가 기능 개선

## Todo
- [x] 마이페이지
- [x] 회원정보 페이지 - 기존 비밀번호 맞는지 검사 (API 추가 필요)
- [x] 회원정보 페이지 - 새 비밀번호로 수정
- [x] POS 페이지 - 카테고리 등록하자마자 해당 카테고리가 선택한 상태
- [x] POS 페이지 - 아이템 가격만 수정할 수 있게 (API 수정 필요)
- [x] POS 페이지 - 카테고리 삭제하면 해당하는 아이템 컴포넌트 다시 빈 화면이 되게 리렌더링
- [x] POS 페이지 - 카테고리랑 아이템 갯수 제한 풀고 스크롤 되게
