### ISSUE TITLE
css 팀원 피드백

### ISSUE THREAD

**Issue by Kwak-Minju** [ssg-salesync/frontend#90]
## Description
- 팀원 피드백 반영
## Todo
- [x] 메인 아래 여백 주기
- [x] 주문완료 / 주문 취소 시 팝업 닫히기
- [x] kiosk location change
- [x] logo 수정 
- [x] button hover

## ETC
- 추가 예정
